### PR TITLE
Fix duplicated text on delete

### LINKED ISSUE #54: Duplicate text when pressing the Delete button
**Steps to reproduce:**
1) Type some text in the field (length > 0)
2) move the cursor at the beginning of the string
3) Press Delete

**Expected result:**
Nothing happens when you delete from the beginning of the string

**Actual result:**
The text in the field is duplicated

### PR DESCRIPTION
**Pull request by ivanross**
As title says, this PR fixes duplicated text on delete (fixes #54) 🙂

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -11,6 +11,7 @@ const CURSOR = chalk.inverse(' ');
 const ENTER = '\r';
 const ARROW_LEFT = '\u001B[D';
 const ARROW_RIGHT = '\u001B[C';
+const DELETE = '\x7F';
```
Comment (sindresorhus) [inline test.js:14]: Use Unicode escape.

File: test.js [hunk 2]
```diff
@@ -132,3 +133,27 @@ test('paste and move cursor', t => {
 	stdin.write(ARROW_RIGHT);
 	t.is(lastFrame(), `AHello WorldB${CURSOR}`);
 });
+
+test('delete at begigging of text', t => {
```
Comment (sindresorhus) [inline test.js:137]: Typo

**Comment by vadimdemedes** [comment]
Thanks!
